# Generated by Django 3.2.9 on 2021-12-11 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-time']},
        ),
    ]
