# Generated by Django 3.2.9 on 2021-12-13 00:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkey',
            name='key',
            field=models.CharField(default=uuid.UUID('9909db6f-04f7-48c9-b39e-04e042dec26b'), max_length=1000),
        ),
    ]
