# Generated by Django 3.2.9 on 2021-12-13 00:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userkey_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkey',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userkey',
            name='key',
            field=models.CharField(default=uuid.UUID('3c50b349-2c9b-4583-928f-2b60a0a6e73f'), max_length=1000),
        ),
    ]
