# Generated by Django 3.2.9 on 2021-12-13 22:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20211212_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkey',
            name='key',
            field=models.CharField(default=uuid.UUID('29f9488d-1b0c-4ac3-bfab-4027e461f781'), max_length=1000),
        ),
    ]
