# Generated by Django 3.2.9 on 2021-12-15 23:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_userkey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkey',
            name='key',
            field=models.CharField(default=uuid.UUID('b700773b-c51c-4507-9879-c2364c4da433'), max_length=1000),
        ),
    ]
