# Generated by Django 3.2.9 on 2021-12-18 22:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_userkey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkey',
            name='key',
            field=models.CharField(default=uuid.UUID('d1966356-5501-4c18-9ffc-9bc485c5436e'), max_length=1000),
        ),
    ]
