# Generated by Django 3.2.9 on 2021-12-18 22:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_userkey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkey',
            name='key',
            field=models.CharField(default=uuid.UUID('5cbea59c-776b-4b2c-8c65-805198d17eae'), max_length=1000),
        ),
    ]
