# Generated by Django 3.2.9 on 2021-12-19 00:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_userkey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkey',
            name='key',
            field=models.CharField(default=uuid.UUID('0c4967d2-3506-4f0d-ade4-e579f59b4450'), max_length=1000),
        ),
    ]
